# Generated by Django 6.0.4 on 2026-04-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_managers_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Дата оплаты"
            ),
        ),
    ]
