# Generated by Django 6.0.4 on 2026-04-26 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_payments_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата оплаты"
            ),
        ),
    ]
