# Generated by Django 6.0.4 on 2026-05-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_payments_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="payment_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="id сессии"
            ),
        ),
    ]
