# Generated by Django 6.0.4 on 2026-05-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_payments_payment_link_payments_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="id сессии"
            ),
        ),
    ]
