# Generated by Django 6.0.4 on 2026-05-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_payments_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
