# Generated by Django 6.0.4 on 2026-05-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_payments_payment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_link",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
