version: "3.9"

services:
  drf_project:
    image: prodeon/myapp:latest
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  db:
    image: postgres:15
    env_file:
      - ./.env
    expose:
      - "5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  celery:
    image: prodeon/myapp:latest
    command: celery -A config worker -l INFO
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    restart: unless-stopped

  celery_beat:
    image: prodeon/myapp:latest
    command: celery -A config beat -l INFO
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    restart: unless-stopped

  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    depends_on:
      - drf_project
    restart: unless-stopped

volumes:
  redis_data: