# Generated by Django 6.0.4 on 2026-04-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teaching", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Превью(картинка)"
            ),
        ),
    ]
