# Generated by Django 6.0.4 on 2026-04-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teaching", "0002_alter_course_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Превью(картинка)"
            ),
        ),
    ]
