# Generated by Django 6.0.4 on 2026-04-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teaching", "0003_alter_lesson_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="teaching.course",
                verbose_name="курс",
            ),
        ),
    ]
