# Generated by Django 6.0.4 on 2026-05-12 15:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teaching", "0006_subscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("user", "course")},
        ),
    ]
